<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use File;
use DB;
use App\CronLog;
use Carbon\Carbon;
use Storage;


class DoFolderMonthBills extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'bills:generateFolder';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create a folder for save all bills generated by plataform';

    protected $cronLog;

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
        $this->cronLog = new CronLog();
        $this->cronLog->created_at = Carbon::now('Europe/Madrid');
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $data = array('year'=>false,'month'=>false);
        $this->cronLog->cron_launch_at = Carbon::now('Europe/Madrid');
        $year  =date('Y');
        $month = date('n');

        if (!Storage::exists('bills/' . $year)) {
            $data['year'] = true;
            Storage::makeDirectory('bills/' . $year);
        }

        if (!Storage::exists('bills/' . $year . '/' . $month)) {
            $data['month'] = true;
            Storage::makeDirectory('bills/' . $year . '/' . $month);
        }

        $this->cronLog->result = serialize($data);
        $this->cronLog->updated_at = Carbon::now('Europe/Madrid');
        $this->cronLog->save();

    }
}
